# Generated by Django 4.2.6 on 2024-03-30 18:09

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=registration.models.custom_upload_to
            ),
        ),
    ]
