# Generated by Django 4.2.6 on 2024-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thread",
            options={"ordering": ["-updated"]},
        ),
        migrations.AddField(
            model_name="thread",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
